variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOT_NET_BIN_PATH: "C:/Program Files/dotnet/dotnet.exe"
  TARGET_REPO: "F:/CIV_CI/Publish_Repo/Publish/"
  TEMP_DIR: "F:/CIV_CI/tempV1/Publish/"

before_script:
 

stages:
  - buildIdentity
  - buildOMS
  - buildWeb
  - buildGateway
  - push
  

buildI:
  stage: buildIdentity
  script:
  - echo "dotnet publish Identity to target dir"
  - '&${DOT_NET_BIN_PATH} publish .\src\IdentityServer\Identity.Web\Identity.Web.csproj -c Release -p:PublishProfile=FolderProfile -o ${TEMP_DIR}\Identity\ '
  cache:
    untracked: true
  only:
    - dev-wisdom

buildII:
  variables:
    GIT_STRATEGY: none
  stage: buildOMS
  script:
  - echo "dotnet publish OMS to target dir"
  - '&${DOT_NET_BIN_PATH} publish .\src\OMS\OMS.Web\OMS.Web.csproj -c Release -p:PublishProfile=FolderProfile -o ${TEMP_DIR}\OMS\ '
  cache:
    untracked: true
  only:
    - dev-wisdom
    
buildIII:
  variables:
    GIT_STRATEGY: none
  stage: buildWeb
  script:
  - echo "dotnet publish Web to target dir"
  - '&${DOT_NET_BIN_PATH} publish .\src\WebApp\Web\Web.csproj -c Release -p:PublishProfile=FolderProfile -o ${TEMP_DIR}\Web\ '
  cache:
    untracked: true
  only:
    - dev-wisdom
    
buildIV:
  variables:
    GIT_STRATEGY: none
  stage: buildGateway
  script:
  - echo "dotnet publish Gateway to target dir"
  - '&${DOT_NET_BIN_PATH} publish .\src\APIGateway\APIGateway.csproj -c Release -p:PublishProfile=FolderProfile -o ${TEMP_DIR}\Gateway\ '
  cache:
    untracked: true
  only:
    - dev-wisdom

  
push:
  variables:
    GIT_STRATEGY: none
  stage: push
  script:
  - echo "packaging now"
  - 'cd ${TARGET_REPO}'
  - 'git reset --hard head'
  - 'git clean -fd'
  - 'git remote set-url origin "https://${GIT_ACCESS_USER}:${GIT_ACCESS_PASSWORD}@g.civnet.cn:8443/CivPublish/Publish.git"'
  - 'git pull origin master'
  - 'robocopy /E ../../tempV1/Publish/ "${TARGET_REPO}" ; 
        IF (${LASTEXITCODE} -le 8) {cmd /c "exit /b 0"}'
  - 'git add . ; git commit -m "auto package Publish."'
  - 'git push origin master'

  allow_failure: false
  only:
    - dev-wisdom
  when: manual
