using System;
using System.Collections.Generic;

#nullable disable

namespace WebApplication1.Models
{
    public partial class 数据实时二供机组
    {
        public int Id { get; set; }
        public string 设备编码 { get; set; }
        public DateTime? 更新时间 { get; set; }
        public DateTime? 采集时间 { get; set; }
        public int? 是否在线 { get; set; }
        public DateTime? 上线时间 { get; set; }
        public float? 在线时长 { get; set; }
        public DateTime? 离线时间 { get; set; }
        public float? 离线时长 { get; set; }
        public int? 是否报警 { get; set; }
        public string 当前报警 { get; set; }
        public float? 报警时长 { get; set; }
        public int? 设备控制方式 { get; set; }
        public int? 变频器1故障报警 { get; set; }
        public int? 变频器2故障报警 { get; set; }
        public int? 变频器3故障报警 { get; set; }
        public int? 变频器4故障报警 { get; set; }
        public int? 变频器5故障报警 { get; set; }
        public int? 变频器6故障报警 { get; set; }
        public int? 进水传感器故障 { get; set; }
        public int? 出水超压报警 { get; set; }
        public int? 进水压力低报警 { get; set; }
        public int? 出水压力低报警 { get; set; }
        public int? 市政无水报警 { get; set; }
        public int? 三相电异常报警 { get; set; }
        public int? Ups电源异常 { get; set; }
        public int? 交流失电报警 { get; set; }
        public int? 出水传感器异常 { get; set; }
        public int? 流量计通讯异常 { get; set; }
        public int? 泵房浸水信号 { get; set; }
        public int? 泵房门开状态 { get; set; }
        public int? 泵房灯开信号 { get; set; }
        public int? 泵房闯入报警 { get; set; }
        public int? 泵房烟雾报警信号 { get; set; }
        public int? 泵房环境高温报警 { get; set; }
        public int? _1水箱高位报警 { get; set; }
        public int? _1水箱低位报警 { get; set; }
        public int? _2水箱高位报警 { get; set; }
        public int? _2水箱低位报警 { get; set; }
        public int? 水箱人孔打开信号 { get; set; }
        public int? 电气柜高温报警 { get; set; }
        public int? 用户管网爆管预警 { get; set; }
        public int? _1电动阀异常 { get; set; }
        public int? _2电动阀异常 { get; set; }
        public int? 预留故障报警2 { get; set; }
        public float? 进水压力 { get; set; }
        public float? 出水压力 { get; set; }
        public int? 泵1状态 { get; set; }
        public int? 泵2状态 { get; set; }
        public int? 泵3状态 { get; set; }
        public int? 泵4状态 { get; set; }
        public int? 泵5状态 { get; set; }
        public int? 泵6状态 { get; set; }
        public float? _1变频器运行频率 { get; set; }
        public float? _2变频器运行频率 { get; set; }
        public float? _3变频器运行频率 { get; set; }
        public float? _4变频器运行频率 { get; set; }
        public float? _5变频器运行频率 { get; set; }
        public float? _6变频器运行频率 { get; set; }
        public float? _1水箱液位 { get; set; }
        public float? _2水箱液位 { get; set; }
        public float? _3水箱液位 { get; set; }
        public float? _4水箱液位 { get; set; }
        public float? 进水瞬时流量 { get; set; }
        public float? 出水瞬时流量 { get; set; }
        public float? 变1电流 { get; set; }
        public float? 变2电流 { get; set; }
        public float? 变3电流 { get; set; }
        public float? 变4电流 { get; set; }
        public float? 变5电流 { get; set; }
        public float? 变6电流 { get; set; }
        public int? 泵1运行时间 { get; set; }
        public int? 泵2运行时间 { get; set; }
        public int? 泵3运行时间 { get; set; }
        public int? 泵4运行时间 { get; set; }
        public int? 泵5运行时间 { get; set; }
        public int? 泵6运行时间 { get; set; }
        public float? 变1功率 { get; set; }
        public float? 变2功率 { get; set; }
        public float? 变3功率 { get; set; }
        public float? 变4功率 { get; set; }
        public float? 变5功率 { get; set; }
        public float? 变6功率 { get; set; }
        public float? 余氯 { get; set; }
        public float? 浊度 { get; set; }
        public float? PH { get; set; }
        public float? 室外温度 { get; set; }
        public float? 泵房温度 { get; set; }
        public float? 泵房湿度 { get; set; }
        public int? _1排水泵状态 { get; set; }
        public int? _2排水泵状态 { get; set; }
        public int? _3排水泵状态 { get; set; }
        public int? _4排水泵状态 { get; set; }
        public float? 设定出水压力 { get; set; }
        public int? 站点在线状态 { get; set; }
        public int? 累计电量 { get; set; }
        public int? 进水累计流量 { get; set; }
        public int? 出水累计流量 { get; set; }
        public int? 泵站编号 { get; set; }
        public float? Plc程序版本号 { get; set; }
        public int? 设备维修状态 { get; set; }
        public int? 设备分时运行方案 { get; set; }
        public float? 出水设定压力 { get; set; }
        public int? _1电动阀在全开位置 { get; set; }
        public int? _1电动阀在全关位置 { get; set; }
        public float? _1电动阀开度 { get; set; }
        public int? _2电动阀在全开位置 { get; set; }
        public int? _2电动阀在全关位置 { get; set; }
        public float? _2电动阀开度 { get; set; }
        public int? 泵房风机状态 { get; set; }
        public float? 噪声 { get; set; }
        public float? 智能电表ua { get; set; }
        public float? 智能电表ub { get; set; }
        public float? 智能电表uc { get; set; }
        public float? 智能电表ia { get; set; }
        public float? 智能电表ib { get; set; }
        public float? 智能电表ic { get; set; }
        public float? 智能表互感器倍率 { get; set; }
        public float? 智能表累计电量 { get; set; }
        public float? 智能电表A相功率 { get; set; }
        public float? 智能电表B相功率 { get; set; }
        public float? 智能电表C相功率 { get; set; }
        public float? 机组总功率 { get; set; }
        public float? 累计电量泵运行时 { get; set; }
        public float? 智能电表功率因素cos { get; set; }
        public float? 智能电表温度 { get; set; }
        public float? 智能电表漏电流 { get; set; }
        public float? _1补水时间 { get; set; }
        public float? _1滞留时间 { get; set; }
        public float? _2补水时间 { get; set; }
        public float? _2滞留时间 { get; set; }
        public int? 泵7状态 { get; set; }
        public int? 泵8状态 { get; set; }
        public float? _7变频器运行频率 { get; set; }
        public float? 变7电流 { get; set; }
        public float? 变7功率 { get; set; }
        public float? 泵7运行时间 { get; set; }
        public float? _8变频器运行频率 { get; set; }
        public float? 变8电流 { get; set; }
        public float? 变8功率 { get; set; }
        public float? 泵8运行时间 { get; set; }
        public int? 变更设备控制方式 { get; set; }
        public int? 控制泵1启停 { get; set; }
        public int? 控制泵2启停 { get; set; }
        public int? 控制泵3启停 { get; set; }
        public int? 控制泵4启停 { get; set; }
        public int? 控制泵5启停 { get; set; }
        public int? 控制泵6启停 { get; set; }
        public float? 设置1电动阀开度 { get; set; }
        public float? 设置2电动阀开度 { get; set; }
        public int? 变频器故障复位 { get; set; }
        public int? 定时切换 { get; set; }
        public float? 加泵延时 { get; set; }
        public int? 开门或关门 { get; set; }
        public int? 开灯或关灯 { get; set; }
        public float? 控制柜风扇启动温度 { get; set; }
        public float? 控制柜风扇停止温度 { get; set; }
        public int? 启停水箱消毒仪 { get; set; }
        public int? 设定运行时段方案 { get; set; }
        public int? 视频预置监控点 { get; set; }
        public int? 数据上传周期 { get; set; }
        public int? 控制排水泵启停 { get; set; }
        public int? 控制泵房风机启停 { get; set; }
        public float? 控制泵房风机启动温度 { get; set; }
        public float? 控制泵房风机停止温度 { get; set; }
        public int? 数据上传长度 { get; set; }
        public int? 控制泵7启停 { get; set; }
        public int? 控制泵8启停 { get; set; }
        public string 采集编码 { get; set; }
        public string 采集协议 { get; set; }
        public int? 顺序 { get; set; }
    }
}
